### PR TITLE
One typo in the README (docutils/writiers → writers)

### PR DESCRIPTION
**Pull request by Naereen**
- Fixing one typo in the README (docutils/writiers → writers);
- Add `markup` for the paths and filenames;
- Add links to the paths and scripts.

### CODE REVIEW

**Comment by cgwrench** [comment]
Hi @Naereen. Thanks very much for this contribution - that typo is a good spot.

Before I merge this fix in, there are a few issues I have with the rest of the changes you've made:

1. Firstly, I've tried to keep line lengths to 80 characters or fewer. Could you please reformat your changes to be consistent with this?

2. The paths you have added are Linux/UNIX specific - this assumes that people on Windows aren't using this project. I deliberately didn't include paths like this in the README in order to avoid cross-platform issues like this. However, I appreciate that having these paths spelled out is helpful. So can you either remove these paths, or add similar paths for Windows (whatever they may be). I am happy to keep the markup changes you've make though.

Thanks for the contribution, Chris.

**Comment by Naereen** [comment]
Alright, I reformated my changes, and added the example path for Windows.


In fact, I just realized that this project is still in a very early stage (the script does not work at all on my Linux machine), and has not been updated in 3 years...

Could you try to conclude it? (it seems useless to polish a README file for a project where the core script is not even finished)

**Comment by cgwrench** [comment]
Thanks - I'll try and review this later when I have access to my dev. machine.

I've clearly marked this project as a work in progress - this was simply a personal project for me to learn more about Docutils. Since I started this my time and focus has been elsewhere. If you want to help progress this project then please do submit a pull request. If you think that "it seems useless to polish a README file for a project where the core script is not even finished", then I'm happy for you to work on the core functionality instead.

If you've found it useful at all then great. If you're having issues with the project, then please raise them as an issue - including as much detail about the error as possible (as it states in the README you've edited).

Once again, thanks for your contribution.

**Comment by Naereen** [comment]
Any chance of merge ?

**Comment by cgwrench** [comment]
Hi @Naereen. Thanks for your contribution.

Unfortunately, I've not had much time to work on this project, and since I started it my time and focus has shifted elsewhere. I'm therefore going to close this pull request and mark the repository as read-only.

I hope you've found this project at least a bit useful.

Once again, thanks for your contribution. And apologies for not giving it the attention it deserves.

**Pull request closed without merging**
