### PR TITLE
MRG: installation setup.py and supporting stuff

### PR DESCRIPTION
**Pull request by matthew-brett**
* Move module into own package;
* Turn tools/rst2md.py into a script "rst2md"
* Add requirements.txt and version dependencies;
* Add .travis.yml and tools/travis_tools for travis testing;
* Use versioneer for version management;
* Add a test of the script output.

### CODE REVIEW

**Comment by cgwrench** [comment]
Thanks for this work @matthew-brett, this looks great. There are quite a few changes so will take me a bit of time to review them all.

**Comment by matthew-brett** [comment]
Oops - sorry - I have been doing more work here.  I'll split this into two PRs.

**Comment by matthew-brett** [comment]
I guess the most controversial thing is renaming `rst2md.py` to `rst2md`.  This follows Debian conventions of scripts not having suffixes, but differs from the default docutils convention.  Can revert if you like...

**Comment by matthew-brett** [comment]
The versioneer stuff is boilerplate from https://pypi.python.org/pypi/versioneer and doesn't need review, I believe.

**Comment by matthew-brett** [comment]
The `scriptrunner.py` file is something I used for several projects including 

* https://github.com/nipy/nibabel 
* https://github.com/nipy/nipy
* https://github.com/nipy/dipy
* https://github.com/matthew-brett/delocate

It's therefore fairly well battle-tested, but another review is always useful.

**Comment by cgwrench** [comment]
Firstly, thanks for all this work. However, I have a few concerns that we can hopefully address before I would be happy to merge in this work.

1. The size of the changes.

   The code added as part of this pull request dwarfs the size of the original code: this project is basically a 250 line file, `markdown.py`. The changes added in this pull request add over 2,500 lines of code: increasing the size of the code by more than 10x. The file `_version.py` on its own is almost double the size of `markdown.py`.

   I believe that some of the boilerplate/infrastructure code is overkill for such a simple project. Manually updating things like version strings would be more than adequate.

2. The scope of the changes.

   This pull request makes a number of changes:

   - Code refactoring
   - Addition of tests
   - Addition of module/packaging code
   - Addition of CI scripts

   I believe that these changes should be split up into separate issues, each with their own associated pull request. This would allow me to review and accept an individual piece of functionality or change, rather than the current situation of accepting all or none of the changes.

3. The addition of thrid party code

   This pull requests adds two files, `versioneer.py` and `scriptrunner.py`, taken from external projects. These represent a significant maintenance overhead. If a bug is found in scriptrunner.py, are you likely to remember all of the projects you've added this script too add undapte all of them? Similarly with `versioneer.py`: fixes to this project won't make their way into this project without someone monitoring the versioneer project for changes.

   These might be better as git submodules, but I would rather not have these dependencies copied and pasted into this project. The need for `Scriptrunner.py` could be removed by testing the appropriate API methods, rather than testing the script rst2md.py (i.e. we could use built in Python testing frameworks to test `Writer.translate` from markdown.py).

4. Additional of unnecessary CI scripts.

   This pull request adds some code to use Travis CI. For a project of this size, I beleive that this is overkill. I am unlikely to set up CI for this project since it is so small, has so few people working on it and so rarely receives changes.

5. Renaming `rst2md.py` to `rst2md`

   Whilst this change does following Debian, and more generally Linux, conventions for scripts, I would rather keep this consistent witht Docutils. Can this change be reverted.


My recommendation for moving forward is to split these changes up as separate issues. I would like to see:

- A simple `setup.py`. For such a simple project hardcoded dependencies and version number are sufficient;
- A simple setup for unit tests.

All other changes can be dropped for now I believe.

**Comment by matthew-brett** [comment]
I do agree that there are many code lines here.

I also know that it can be very hard to attract developers - I have quite a few projects of my own, and of course there is a high barrier to working on someone else's code.

The trick is to make everything as safe and as smooth as possible for contributions.

To respond to your questions one by one:

* For me, the question is not the size of the code, but the maintenance burden.  For example, does the versioneer code have a maintenance burden?   I think the answer is very close to no.   Does it have a maintenance advantage?  Yes, because it makes the release procedure less error-prone and easier to explain.   For example, here's the release procedure for another project I have using versioneer : https://github.com/matthew-brett/texext/blob/master/doc/devel/make_release.rst

* For the scriptrunner - I used to feel the same way as you, that it wasn't that important to test the scripts, but long experience forced me to change my opinion on that, because I often found that the code was running, but the scripts were not.   Is the scriptrunner code a maintenance burden?   Yes, but small.   If it fails, all that happens is that it's harder to run the tests.  It can certainly suffer from Python version problems, but it's currently running with 4 projects being tested on Pythons 2.6 through 3.5 on all common platforms and some uncommon ones, so the chances of new problems appearing in this project is fairly small.   Yes, I would certainly maintain scriptrunner here, if you agreed to leave it in.  You've probably seen I am constantly active on github over many years, so even if I miss this myself, I would respond quickly via an issue.  While I am not responding, all you have is a test failure, not broken code.

* I must say I don't agree about travis-ci testing.  I think that's crucial for maintaining code quality and making it easier for others to contribute.   It makes a big difference to me if I know that the code I am contributing to has got a solid automatically-run test rig, and it helps me review other people's changes for my other projects.   It's true that the travis file is a moderate maintenance burden, but again, I'm happy to do that maintenance.   If you don't want it, I'll certainly have it running on my own fork, so it will make things harder for me, in the sense that I'll have to remove it for every PR I do.

* No problem for renaming `rst2md`.

**Comment by cgwrench** [comment]
I'm afraid we're going to disagree here.

1. In terms of the maintenance burden, every line of [code is a liability](http://chrismdp.com/2012/09/code-is-a-liability/). To say that including hundreds of lines of additional code into a project has close to no maintenance burden is simply incorrect.

   If we do need to depend on a tool such as versioner, this should be included in the project as an external tool/dependency, which can simply be updated when a new version is released. Including the source code of a dependency directly into the source code of a project is not the correct way to utilise this tool.

2. I don't believe that testing scripts is unimportant. However, I believe that rst2md.py is not the correct place to implement the majority of tests: testing rst2md.py is an integration test, not a unit test. Tests for the bulk of the functionality of this project should focus on the appropriate API methods. Tests that ensure that rst2md.py can be invoked correctly could then be added to supplement these unit tests.

3. I'm a big believer in the importance of CI. However, I'm not currently prepared to support the maintenance of a Travis CI setup. Whilst a good CI setup is important, for an immature project such as this, a Travis CI setup would only give the impression that the project is more robustly tested and maintained than it actually is. For a project that doesn't receive many changes, I believe that documenting how to run the tests is sufficient for now.

For future reference, I would definitely recommend discussing potential changes with project maintainers before starting work on the changes. This gives the maintainers a chance to approve and influence the changes before you start work on the changes, avoiding wasted effort if the change is not appropriate or if should take a different approach.

I see that you have created a number of new pull requests, so I will close this pull request in order to focus on the new requests.

**Comment by matthew-brett** [comment]
Thanks for the feedback.

I was working on this anyway for a project that I am soon going to ship, so I needed the markdown conversion to work fairly well and have good coverage.

I have many projects of my own, so I know how frustrating it is when people do work on my code, but don't try and help feed it back, so I put the extra effort in here, hoping to fix that.

My overall hope was that, even if I was doing most of the maintenance, there would be a good stable release to pypi that I could depend on - hence the various standard tools I added.

But, now I don't think that's going to happen in the short term, so I will ship a tested copy of markdown.py in my own project, of course with the correct license and credit.   I'll submit pull-requests from time to time when I've done a reasonable amount of work.

Thanks for sharing.

**Pull request closed without merging**
