### PR TITLE
MRG: adding more tests and new capabilities

### PR DESCRIPTION
**Pull request by matthew-brett**
This is based on top of https://github.com/cgwrench/rst2md/pull/3.

Add ability to output for literal blocks, math blocks, literals inline, math
inline.

Refactor newline handling so each node leaves the newlines in a state ready to put in new markdown.

Add some new test files and test routines.

### CODE REVIEW

**Comment by cgwrench** [comment]
Hi @matthew-brett. Thanks for this. Please see my comments on #3. My concern with this pull request is that it is trying to do too much. If you could split this up to just implement the inline math and math blocks then that would be great and I can accept this quickly. For the associated tests, please leave these out for now, until we have a solution to #3.

**Comment by matthew-brett** [comment]
Ok - I'll keep working on this for a bit, and then try and split the changes up.

The problem is that - for example - the math changes need the newline handling changes in order to work.

I'll try and think of some way of segmenting these changes after a day or so more of work.

**Comment by matthew-brett** [comment]
Ok - I refactored on top of the minimal setup.py.  I've added quite a few new constructs, most important being the ability to have indented levels, such as nested lists.   There are test files testing each addition.  I think this is ready for review now.

**Comment by cgwrench** [comment]
Hi @matthew-brett. Thanks for your contribution.

Unfortunately, I've not had much time to work on this project, and since I started it my time and focus has shifted elsewhere. I'm therefore going to close this pull request and mark the repository as read-only.

I hope you've found this project at least a bit useful.

Once again, thanks for your contribution. And apologies for not giving it the attention it deserves.

**Pull request closed without merging**
